# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(verbose_name='\u5b66\u671f')),
                ('course_type', models.CharField(choices=[(b'online', '\u7f51\u7edc\u73ed'), (b'offline_weekend', '\u9762\u6388\u73ed(\u5468\u672b)'), (b'offline_fulltime', '\u9762\u6388\u73ed(\u8131\u4ea7)')], default=b'offline_weekend', max_length=64)),
                ('start_date', models.DateField()),
                ('graudate_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('online_price', models.IntegerField()),
                ('offline_price', models.IntegerField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='courseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(verbose_name='\u7b2c\u51e0\u8282\u8bfe')),
                ('course_date', models.DateField(auto_now_add=True, verbose_name='\u4e0a\u8bfe\u65f6\u95f4')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.classList')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[(b'online', '\u7f51\u7edc\u73ed'), (b'offline_weekend', '\u9762\u6388\u73ed(\u5468\u672b)'), (b'offline_fulltime', '\u9762\u6388\u73ed(\u8131\u4ea7)')], default=b'offline_weekend', max_length=64)),
                ('consult_memo', models.TextField()),
                ('source_type', models.CharField(choices=[(b'qq', 'qq\u7fa4'), (b'referral', '\u5185\u90e8\u8f6c\u4ecb\u7ecd'), (b'51cto', '51cto'), (b'agent', '\u62db\u751f\u4ee3\u7406'), (b'others', '\u5176\u5b83')], max_length=64)),
                ('status', models.CharField(choices=[(b'signed', '\u5df2\u62a5\u540d'), (b'unregistered', '\u672a\u62a5\u540d'), (b'graduated', '\u5df2\u6bd5\u4e1a'), (b'drop-off', '\u9000\u5b66')], max_length=64)),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u54a8\u8be2\u65e5\u671f')),
                ('class_list', models.ManyToManyField(blank=True, to='crm.classList')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_record', models.TextField(verbose_name='\u8ddf\u8e2a\u8bb0\u5f55')),
                ('track_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, '\u8fd1\u671f\u65e0\u62a5\u540d\u8ba1\u5212'), (2, '2\u4e2a\u6708\u5185\u62a5\u540d'), (3, '1\u4e2a\u6708\u5185\u62a5\u540d'), (4, '2\u5468\u5185\u62a5\u540d'), (5, '1\u5468\u5185\u62a5\u540d'), (6, '2\u5929\u5185\u62a5\u540d'), (7, '\u5df2\u62a5\u540d')], verbose_name='\u72b6\u6001')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('addr', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[(b'checked', '\u5df2\u7b7e\u5230'), (b'late', '\u8fdf\u5230'), (b'noshow', '\u7f3a\u52e4'), (b'leave_early', '\u65e9\u9000')], max_length=64, verbose_name='\u72b6\u6001')),
                ('score', models.IntegerField(choices=[(100, b'A+'), (90, b'A'), (85, b'B+'), (80, b'B'), (70, b'B-'), (60, b'C+'), (50, b'C'), (40, b'C-'), (0, b'D'), (-1, b'N/A'), (-100, b'COPY'), (-1000, b'FAIL')], default=-1, verbose_name='\u672c\u8282\u6210\u7ee9')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.courseRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customertrackrecord',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='\u8bfe\u7a0b\u987e\u95ee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='\u8bfe\u7a0b'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(to='crm.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together=set([('class_obj', 'day_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('course', 'semester', 'course_type')]),
        ),
    ]
