# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('can_del_customer', '\u53ef\u5220\u9664\u5ba2\u6237\u8bb0\u5f55'),)},
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[(b'online', '\u7f51\u7edc\u73ed'), (b'offline_weekend', '\u9762\u6388\u73ed(\u5468\u672b)'), (b'offline_fulltime', '\u9762\u6388\u73ed(\u8131\u4ea7)')], max_length=64),
        ),
    ]
